- hosts: all
  vars_files:
    - secret.yml
  roles:
    - CLEANUP
    - monit # make sure sshd running after netbird
- hosts: eth_nodes
  roles:
    - wireguard-clients # test first with node-fast21.yml
    - mev-boost
    - lighthouse
    - besu

