# Install mev-boost dependencies
- name: Install mev-boost dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - wget
    - tar

# Download mev-boost tar.gz file
- name: Download mev-boost tar.gz file
  shell: "wget -P /tmp https://github.com/flashbots/mev-boost/releases/download/v{{ mevboost_version }}/mev-boost_{{ mevboost_version }}_linux_amd64.tar.gz"
  args:
    creates: "/tmp/mev-boost_{{ mevboost_version }}_linux_amd64.tar.gz"

# Extract the tar.gz file
- name: Extract the tar.gz file
  shell: "tar -xzf /tmp/mev-boost_{{ mevboost_version }}_linux_amd64.tar.gz -C /tmp"

# Copy mev-boost to /usr/bin
- name: Copy mev-boost to /usr/bin
  shell: "cp -f /tmp/mev-boost /usr/bin/mev-boost"

- name: allow mev-boost port 18550
  ufw:
    rule: allow
    port: 18550
    proto: tcp
    state: enabled

# Create mev-boost service
- name: Create mev-boost service
  copy:
    content: |
      [Unit]
      Description=MEV Boost service
      After=network.target

      [Service]
      User=root
      Group=root
      ExecStart=/usr/bin/mev-boost \
        -mainnet \
        -relay-check \
        -addr 0.0.0.0:18550 \
        -relay https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.net \
        -relay https://0xad0a8bb54565c2211cee576363f3a347089d2f07cf72679d16911d740262694cadb62d7fd7483f27afd714ca0f1b9118@bloxroute.ethical.blxrbdn.com \
        -relay https://0x9000009807ed12c1f08bf4e81c6da3ba8e3fc3d953898ce0102433094e5f22f21102ec057841fcb81978ed1ea0fa8246@builder-relay-mainnet.blocknative.com \
        -relay https://0xb0b07cd0abef743db4260b0ed50619cf6ad4d82064cb4fbec9d3ec530f7c5e6793d9f286c4e082c0244ffb9f2658fe88@bloxroute.regulated.blxrbdn.com \
        -relay https://0x8b5d2e73e2a3a55c6c87b8b6eb92e0149a125c852751db1422fa951e42a09b82c142c3ea98d0d9930b056a3bc9896b8f@bloxroute.max-profit.blxrbdn.com \
        -relay https://0x98650451ba02064f7b000f5768cf0cf4d4e492317d82871bdc87ef841a0743f69f0f1eea11168503240ac35d101c9135@mainnet-relay.securerpc.com \
        -relay https://0x84e78cb2ad883861c9eeeb7d1b22a8e02332637448f84144e245d20dff1eb97d7abdde96d4e7f80934e5554e11915c56@relayooor.wtf \
        -relay https://0xa1559ace749633b997cb3fdacffb890aeebdb0f5a3b6aaa7eeeaf1a38af0a8fe88b9e4b1f61f236d2e64d95733327a62@relay.ultrasound.money

      Restart=always

      [Install]
      WantedBy=default.target
    dest: /etc/systemd/system/mev-boost.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

# Enable and start mev-boost service
- name: Enable and start mev-boost service
  systemd:
    name: mev-boost
    state: started
    enabled: yes

- name: Send ntfy.sh update
  uri:
    url: "{{ ntfy_url_netdata }}"
    headers:
      Tittle: "mev-boost update {{ inventory_hostname }}"
      Authorization: "Bearer {{ ntfy_token }}"
    method: POST
    body: "{{ inventory_hostname }} Mev-boost update done"
    force_basic_auth: true

- name: current mev-boost version
  shell: "mev-boost -version"
  register: mevboost_version
- debug: msg="{{ mevboost_version.stdout }}"
  
